# G20/OECD INFE Core competencies framework on financial literacy for adults (2016). Paráfrasis en español de todas las competencias.
# Dimensiones: C = conciencia, conocimiento y comprensión · H = habilidades y conducta · A = confianza, motivación y actitudes
MARCO = "OCDE adultos (2016)"
TEMAS = [
("A", "Dinero y transacciones", "A1", "Dinero y monedas", [
 ("C", "Sabe que el dinero tiene distintas formas, incluidas las digitales"),
 ("C", "Entiende que el poder de compra del dinero cambia con el tiempo"),
 ("H", "Cuida el dinero en todas sus formas"),
 ("H", "Busca formas de reducir el efecto de la inflación en su dinero"),
 ("A", "Quiere tomar decisiones sobre su dinero que mejoren su bienestar financiero"),
 ("A", "Reconoce que el bienestar también depende de cosas que no son dinero"),
 ("C", "Entiende la relación entre los medios de pago (vales, tarjetas prepagadas, débito, pagos en línea) y el dinero"),
 ("C", "Sabe cómo enviar dinero de forma segura a otras personas o entidades"),
 ("H", "Considera ventajas y desventajas de cada forma de dinero al elegir cuál usar"),
 ("C", "Entiende qué es el curso legal"),
 ("C", "Sabe reconocer billetes y monedas auténticos y qué hacer con uno falso"),
 ("C", "Sabe que billetes y monedas pueden salir de circulación y cómo cambiarlos"),
 ("H", "Actúa si cree que un billete o moneda es falso"),
 ("H", "Cambia billetes y monedas que salen de circulación dentro del plazo"),
 ("C", "Sabe aplicar el tipo de cambio y que comisiones y tipos de cambio varían por proveedor y en el tiempo"),
 ("C", "Entiende cómo el tipo de cambio afecta remesas, viajes y compras"),
 ("H", "Convierte precios en moneda extranjera a su moneda"),
 ("H", "Considera comisiones y tipo de cambio al enviar o cambiar dinero"),
 ("A", "Se siente capaz de hacer operaciones en otras monedas cuando hace falta"),
 ("A", "Sabe que el dinero significa cosas distintas para distintas personas"),
]),
("A", "Dinero y transacciones", "A2", "Ingreso", [
 ("C", "Conoce fuentes de ingreso laboral y no laboral, incluidos apoyos de gobierno y sus requisitos"),
 ("H", "Evalúa cuánto ingreso necesita hoy"),
 ("H", "Busca un ingreso suficiente al menos para sus gastos de vida"),
 ("H", "Aprovecha al máximo su ingreso"),
 ("A", "Puede hablar de su ingreso con otras personas cuando hace falta"),
 ("C", "Sabe por qué el ingreso neto puede variar"),
 ("H", "Identifica formas legales de aumentar su ingreso"),
 ("A", "Quiere un ingreso suficiente para el nivel de vida que necesita hoy y mañana"),
 ("C", "Entiende el recibo de pago, el ingreso bruto y neto, y por qué registrar su ingreso"),
 ("H", "Revisa y guarda recibos de pago y compara lo que recibe con lo esperado"),
 ("H", "Usa ingreso bruto o neto según la decisión"),
 ("C", "Entiende que algunos descuentos de nómina construyen patrimonio y otros pagan gastos"),
 ("H", "Compara empleos considerando el paquete completo (prestaciones, ahorro, seguros)"),
 ("C", "Entiende que los activos y las inversiones también generan ingreso"),
 ("C", "Sabe que en la vejez pocos tienen ingreso por trabajo y la importancia de otra fuente"),
 ("H", "Estima de forma realista su ingreso futuro"),
 ("H", "Aparta parte de su ingreso para el retiro"),
 ("C", "Conoce caminos laborales, incluido emprender, y cómo afectan su ingreso"),
 ("H", "Da pasos concretos hacia una carrera o una idea de negocio"),
 ("A", "Se siente capaz de seguir una carrera, emprender o cambiar de empleo"),
]),
("A", "Dinero y transacciones", "A3", "Pagos, precios y compras", [
 ("C", "Sabe calcular precios por unidad y que un mismo producto cuesta distinto según lugar y momento"),
 ("C", "Sabe que hay sustitutos más baratos, incluidos de segunda mano"),
 ("H", "Compara precios entre proveedores cuando conviene"),
 ("H", "Busca pagar un precio justo"),
 ("A", "Se siente capaz de negociar y de decir no a una oferta que no quiere"),
 ("C", "Sabe evaluar riesgos y beneficios de cada forma de pago"),
 ("C", "Sabe que algunas formas de pago son crédito y encarecen la compra, y que afectan el flujo de dinero"),
 ("H", "Aprovecha la tecnología para pagar cuando conviene"),
 ("H", "Elige cómo pagar considerando el costo total del medio de pago"),
 ("C", "Sabe que hay errores en cobros y cómo detectarlos en facturas, recibos y tickets"),
 ("H", "Revisa pagos, cambio, recibos y facturas; pide y guarda comprobantes"),
 ("H", "Lleva registro de todo lo que gasta"),
 ("A", "Se siente capaz de reclamar un error en un cobro"),
 ("C", "Reconoce el poder de la publicidad, las ofertas y los medios sobre lo que quiere comprar"),
 ("C", "Entiende el costo de oportunidad: lo que gasta en algo ya no está para otra cosa"),
 ("H", "Tiene estrategias contra la publicidad y la presión social para no gastar de más"),
 ("H", "Considera el valor total de una compra, no solo el precio"),
 ("A", "Resiste la presión de compras no planeadas"),
 ("C", "Sabe que impuestos, tipo de cambio e inflación cambian el precio final y el futuro"),
 ("H", "Calcula el precio final y decide si comprar ahora o después"),
 ("C", "Entiende el costo hundido: decide por lo que podrá pagar, no por lo ya gastado"),
 ("C", "Sabe que algunas compras traen gastos continuos (mantenimiento, suscripciones)"),
 ("H", "Considera suscripciones y pagos repetidos a largo plazo"),
 ("H", "Decide con información sobre pagar a plazos y cumple los pagos acordados"),
]),
("A", "Dinero y transacciones", "A4", "Registros y contratos", [
 ("C", "Entiende lo que implica firmar un contrato con una institución financiera"),
 ("H", "Confirma que entiende términos legales y financieros antes de firmar"),
 ("A", "Pide consejo antes de firmar un contrato"),
 ("C", "Sabe la importancia de guardar ciertos documentos donde pueda consultarlos"),
 ("H", "Revisa registros y contratos y los archiva en orden"),
 ("H", "Pregunta dudas y pide corregir errores en registros y contratos"),
 ("H", "Pide registros y contratos por escrito cuando no se los dan"),
]),
("B", "Planear y administrar", "B1", "Presupuesto", [
 ("C", "Sabe qué es un presupuesto, cómo hacerlo y cuánto puede ahorrar y gastar"),
 ("C", "Entiende por qué conviene hacer y seguir un presupuesto"),
 ("H", "Hace un presupuesto regular, con otras personas si aplica, y con herramientas"),
 ("H", "Usa el presupuesto para planear ingreso, ahorro y gasto"),
 ("A", "Quiere dedicar tiempo a hacer y seguir su presupuesto"),
 ("C", "Sabe dar seguimiento a ingresos y gastos y que el estado de cuenta puede no estar al día"),
 ("H", "Considera ingresos y compromisos regulares, irregulares y cambiantes"),
 ("H", "Sigue el presupuesto, registra gastos y compara lo real con lo planeado"),
 ("H", "Ajusta el presupuesto ante un gasto inesperado o una baja de ingreso"),
 ("A", "Considera el presupuesto completo al decidir un gasto"),
 ("C", "Sabe incluir gastos ocasionales (regalos, fiestas, vacaciones) y un margen libre"),
 ("C", "Entiende la importancia de mirar el mediano y largo plazo al presupuestar"),
 ("H", "Distingue necesidades y deseos y prioriza"),
 ("H", "Revisa el presupuesto cuando prevé un faltante"),
 ("A", "Mira más allá de lo inmediato y se siente capaz de ajustar su presupuesto"),
]),
("B", "Planear y administrar", "B2", "Administrar ingresos y gastos", [
 ("C", "Entiende que hay que administrar el dinero activamente, no solo observarlo"),
 ("H", "Calcula su ingreso neto"),
 ("H", "Distingue gastos fijos y variables"),
 ("H", "Prioriza lo esencial sobre lo discrecional"),
 ("H", "Da seguimiento a ingresos y gastos y ajusta"),
 ("A", "Se siente capaz de decidir por sí misma sobre ingresos, gastos y prioridades"),
 ("C", "Entiende la importancia de planear gastos irregulares y sabe opciones para imprevistos"),
 ("C", "Sabe cuánto necesitaría si perdiera su ingreso"),
 ("H", "Aparta dinero para gastos irregulares"),
 ("H", "Busca ajustar ingresos o gastos cuando hace falta"),
 ("H", "Planea reducir gastos esenciales muy grandes que afectan su nivel de vida"),
 ("C", "Sabe que las etapas de la vida y los eventos familiares cambian ingresos y gastos"),
 ("C", "Sabe que la familia, la comunidad y la cultura influyen en cómo maneja el dinero"),
 ("H", "Separa el dinero del negocio del de la casa"),
 ("A", "Asume la responsabilidad de manejar sus finanzas (y las del hogar)"),
 ("A", "Se siente cómoda hablando de dinero con personas cercanas"),
 ("A", "Se siente capaz de manejar las finanzas de otra persona si tiene la responsabilidad legal"),
 ("H", "Decide con información qué hacer con ingresos extraordinarios: regalos, premios, herencias"),
]),
("B", "Planear y administrar", "B3", "Ahorro", [
 ("C", "Entiende los beneficios de metas de ahorro, de ahorrar pronto y con regularidad, y de «págate primero»"),
 ("H", "Define una meta de ahorro con plazo y forma de lograrla"),
 ("H", "Ahorra cada vez que recibe ingreso"),
 ("H", "Prioriza el ahorro sobre algunos gastos discrecionales"),
 ("H", "Tiene ahorro de emergencia"),
 ("A", "Cree que puede lograr sus metas de ahorro y fija metas realistas"),
 ("A", "Ve el ahorro como parte básica del presupuesto"),
 ("C", "Entiende el beneficio de un fondo de emergencia y de tener parte del ahorro disponible"),
 ("A", "Valora la resiliencia que da el ahorro y quiere aumentarlo"),
 ("C", "Sabe evaluar qué tan seguro es cada método de ahorro"),
 ("H", "Cuida que su ahorro esté seguro"),
 ("H", "Considera la tasa de interés real de su ahorro"),
 ("C", "Entiende el interés compuesto en el ahorro"),
 ("H", "Sigue ahorrando aunque las tasas sean bajas"),
 ("C", "Conoce opciones de ahorro, sus comisiones, tasas y beneficios fiscales, y dónde conseguirlas"),
 ("C", "Entiende que la opción de ahorro depende del plazo de la meta"),
 ("H", "Investiga opciones de ahorro y revisa cómo crece su ahorro"),
]),
("B", "Planear y administrar", "B4", "Invertir", [
 ("C", "Sabe la diferencia entre ahorrar e invertir"),
 ("C", "Sabe que unas inversiones son más líquidas que otras y que su valor sube o baja"),
 ("H", "Tiene un colchón líquido antes de invertir"),
 ("A", "Se siente capaz de pensar si una meta se puede lograr invirtiendo"),
 ("C", "Conoce riesgo y rendimiento potencial de distintas inversiones"),
 ("C", "Entiende la diversificación y la distribución de activos"),
 ("C", "Sabe el riesgo de invertir sin información"),
 ("C", "Entiende tolerancia al riesgo, horizonte y objetivos"),
 ("H", "Investiga, decide según su perfil, diversifica y revisa sus inversiones"),
 ("A", "Investiga antes de invertir, decide sola o con ayuda y cuestiona ofertas demasiado buenas"),
 ("C", "Sabe que hay comisiones y cómo inflación, tasas y tipo de cambio afectan sus planes"),
 ("C", "Sabe calcular cuánto sube o baja una inversión en porcentaje"),
 ("C", "Distingue ganancias o pérdidas realizadas y no realizadas"),
 ("H", "Hace los cálculos para dar seguimiento a sus inversiones"),
 ("C", "Sabe que pensiones, seguros con ahorro y fondos combinan inversiones"),
 ("A", "Investiga en qué invierten sus productos para decidir también con criterios éticos"),
 ("C", "Sabe que el precio de un fondo o acción cambia cada día y no siempre sigue al mercado"),
 ("H", "Considera costos de invertir y de salir antes de decidir"),
 ("C", "Sabe que el oro y otros bienes también suben o bajan"),
 ("C", "Sabe que las emociones afectan las decisiones de inversión"),
 ("H", "Controla sus emociones al invertir"),
]),
("B", "Planear y administrar", "B5", "Planear a largo plazo y construir patrimonio", [
 ("C", "Entiende la importancia de ver el largo plazo aunque lo urgente apriete"),
 ("H", "Planea para eventos futuros, buenos y malos, con efectos financieros"),
 ("A", "Valora planear a largo plazo y se siente capaz de ajustar sus planes"),
 ("C", "Entiende que el largo plazo requiere productos distintos a los del fondo de emergencia"),
 ("H", "Toma decisiones a tiempo y tiene estrategias contra la procrastinación"),
 ("H", "Equilibra necesidades inmediatas con metas de largo plazo"),
 ("H", "Ajusta sus planes con el tiempo y revisa el valor de sus bienes y deudas"),
 ("H", "Considera variaciones previsibles, todos sus bienes y deudas, y que su familia o comunidad pueda necesitar apoyo"),
 ("A", "Se siente capaz de poner sus planes en marcha y valora cuando se cumplen"),
 ("C", "Entiende la importancia de planear el final de la vida: dependientes, deudas, bienes y testamento"),
 ("H", "Deja resuelto cómo cubrir a sus dependientes y repartir bienes y deudas, y lo revisa"),
 ("A", "Piensa en las necesidades de largo plazo de sus dependientes"),
]),
("B", "Planear y administrar", "B6", "Retiro", [
 ("C", "Entiende por qué asegurar su vejez y ahorrar para el retiro desde joven"),
 ("H", "Planea su seguridad financiera para la vejez con todos sus recursos y compromisos"),
 ("A", "Tiene una actitud positiva hacia el retiro"),
 ("C", "Sabe quién tiene derecho a pensión pública y cuánto, y los tipos de pensión del país"),
 ("H", "Aprovecha incentivos al ahorro para el retiro (aportación del patrón, beneficios fiscales)"),
 ("C", "Entiende que hay que planear la etapa de gastar el ahorro del retiro, no solo la de juntarlo"),
 ("C", "Conoce las formas de recibir su pensión y los riesgos de retirar o pedir prestado sobre ella antes"),
 ("H", "Sigue su plan de retiro y lo ajusta"),
 ("H", "Administra con decisión el uso de su ahorro en el retiro"),
 ("H", "Prevé si sus gastos subirán o bajarán en el retiro"),
 ("A", "Equilibra su nivel de vida actual con mejores opciones en la vejez"),
 ("C", "Distingue ahorro para el retiro obligatorio y voluntario, y la inscripción automática"),
 ("H", "Considera el efecto de los empujones (inscripción automática, aportaciones mínimas)"),
]),
("B", "Planear y administrar", "B7", "Crédito", [
 ("C", "Entiende cómo un crédito reduce su ingreso disponible futuro y que debe evaluar si puede pagarlo"),
 ("C", "Conoce tipos de crédito, para qué sirven, ventajas y desventajas"),
 ("H", "Usa crédito solo cuando hace falta y paga a tiempo"),
 ("A", "Piensa en las consecuencias y busca alternativas antes de pedir prestado"),
 ("A", "Se siente capaz de elegir el crédito y el otorgante adecuados"),
 ("C", "Entiende por qué pagar más del mínimo y el riesgo del crédito revolvente"),
 ("H", "Paga lo más posible en créditos revolventes y evalúa pagar por adelantado"),
 ("H", "Maneja sus créditos dentro de su presupuesto y evalúa el costo total antes de pedir"),
 ("A", "Se siente capaz de manejar sus créditos"),
 ("C", "Distingue crédito para generar ingreso o patrimonio del crédito para consumo"),
 ("H", "Considera si el crédito le ayudará a generar ingreso"),
 ("C", "Conoce el riesgo de pedir prestado para cubrir un faltante de ingreso"),
 ("C", "Sabe si un crédito tiene garantía y sus pros y contras"),
 ("H", "Elige el crédito por tasa, costo total, flexibilidad y pago periódico"),
 ("C", "Sabe si la tasa es fija o variable, el interés compuesto en deudas y el plazo"),
 ("C", "Conoce riesgos de prestamistas formales e informales"),
 ("C", "Conoce el riesgo de endeudarse en otra moneda"),
 ("H", "Evalúa riesgos y consecuencias de cada otorgante"),
 ("C", "Sabe que el sobregiro es crédito y tiene costo"),
 ("H", "Mantiene saldo positivo como parte de su presupuesto"),
 ("C", "Sabe que la publicidad y los trámites fáciles tientan a endeudarse"),
 ("C", "Sabe que las tiendas ofrecen crédito para que compres más, que «sin intereses» puede cobrar después y que «compra ahora, paga después» es crédito"),
 ("H", "Suma el costo del crédito al del producto y evalúa si podrá liquidar antes de que termine el periodo sin intereses"),
 ("A", "Se siente capaz de rechazar crédito que no quiere"),
 ("C", "Sabe que bonos o regalos pueden no contar como ingreso para un crédito"),
 ("C", "Sabe que las instituciones consultan su historial y cómo un buen historial baja el costo"),
 ("C", "Sabe qué cuenta en su historial y cómo consultarlo y corregirlo"),
 ("H", "Pregunta qué información usan para evaluar su capacidad de pago"),
 ("H", "Cuida y mejora su historial de crédito"),
 ("C", "Sabe que pueden pedir un aval y lo que implica pedirle a alguien que lo sea"),
 ("H", "Considera el efecto social y financiero de pedir un aval"),
 ("C", "Sabe que un crédito se puede renegociar"),
 ("H", "Se mantiene informada y renegocia condiciones desfavorables"),
]),
("B", "Planear y administrar", "B8", "Deudas", [
 ("C", "Entiende el peso de estar endeudada y su relación con el bienestar"),
 ("C", "Sabe a dónde acudir para reducir su deuda"),
 ("H", "Actúa pronto para evitar problemas de deuda"),
 ("A", "Quiere resolver antes de que la deuda sea una carga"),
 ("C", "Sabe administrar los pagos de sus deudas"),
 ("C", "Sabe que las cuentas sin pagar también son deuda y que el atraso cuesta"),
 ("H", "Prioriza pagos de deudas y servicios sobre gastos discrecionales"),
 ("H", "Evita atrasarse aunque cambien sus circunstancias"),
 ("A", "Asume la responsabilidad de su deuda"),
 ("C", "Sabe dónde pedir ayuda con deudas problemáticas"),
 ("C", "Entiende qué deudas priorizar, qué pasa con un crédito con garantía y sus derechos como deudora"),
 ("H", "Avisa a su acreedor antes del vencimiento si no podrá pagar"),
 ("A", "Se siente capaz de hablar con sus acreedores"),
 ("C", "Entiende la relación deuda-ingreso y el efecto de no pagar en su historial"),
 ("H", "Decide con información antes de pedir prestado para pagar deudas"),
]),
("C", "Riesgo y recompensa", "C1", "Identificar riesgos", [
 ("C", "Conoce los riesgos financieros, incluidos los de los productos y los asegurables"),
 ("C", "Sabe que algunos riesgos se reducen con acciones concretas"),
 ("H", "Considera riesgos externos: ambientales, de salud, de seguridad y económicos"),
 ("A", "Quiere conocer su tolerancia al riesgo"),
 ("A", "Evalúa riesgos sin dejarse llevar por publicidad o noticias"),
 ("C", "Conoce el efecto financiero de vivir muchos años y de depender del ingreso de otra persona"),
 ("C", "Sabe que la incertidumbre política o económica y los desastres afectan sus finanzas"),
 ("C", "Sabe el riesgo de no tener seguro ante eventos caros y poco probables"),
 ("C", "Conoce riesgos de productos: elegir mal, tasa variable, tasa fija, otra moneda"),
 ("H", "Evalúa los riesgos de sus decisiones de vida y de compras o proyectos grandes"),
 ("H", "Considera perder el empleo, más gastos o el ingreso por enfermedad, discapacidad o muerte"),
 ("A", "Quiere reducir riesgos y decide con calma cuando aparecen"),
 ("C", "Sabe que hay datos para evaluar riesgos"),
 ("H", "Usa información disponible para evaluar riesgos"),
 ("A", "Quiere entender la información, incluidas estadísticas"),
]),
("C", "Riesgo y recompensa", "C2", "Redes de protección y seguros", [
 ("C", "Sabe crear un colchón y calcular cuánto tardará en juntar tres meses de ingreso"),
 ("C", "Entiende el papel del seguro"),
 ("H", "Tiene un colchón o un plan para crearlo"),
 ("A", "Quiere crear su colchón y asegurarse ante eventos adversos"),
 ("C", "Entiende que algunos riesgos se manejan sin seguro y qué implica no tener seguro o tener de más"),
 ("C", "Sabe cuándo el seguro es obligatorio y qué seguro sirve para cada situación"),
 ("H", "Considera el seguro cuando identifica un riesgo y usa el adecuado"),
 ("H", "Revisa que su seguro siga cubriendo lo necesario"),
 ("H", "Reclama al seguro cuando corresponde"),
 ("C", "Sabe cuándo el gobierno apoya a hogares en dificultad"),
 ("H", "Mantiene un colchón adecuado con ahorro y otros productos"),
]),
("C", "Riesgo y recompensa", "C3", "Equilibrar riesgo y rendimiento", [
 ("C", "Sabe que si se puede ganar mucho, también se puede perder mucho"),
 ("H", "Identifica riesgos y beneficios de cada decisión"),
 ("A", "Desconfía de rendimientos altos antes de ver los riesgos"),
 ("C", "Entiende la relación riesgo-rendimiento y para qué diversificar"),
 ("H", "Compara riesgo y rendimiento de productos"),
 ("H", "Considera crecer su patrimonio y su seguridad al invertir"),
 ("H", "Considera el riesgo de usar crédito para gastos no necesarios"),
]),
("D", "Panorama financiero", "D1", "Regulación y protección al usuario", [
 ("C", "Entiende el papel de los reguladores y autoridades financieras"),
 ("C", "Sabe que las instituciones deben tratarla con justicia"),
 ("H", "Verifica que la institución esté regulada y supervisada antes de contratar"),
 ("A", "Quiere elegir instituciones confiables"),
 ("C", "Conoce el seguro de depósitos, cuánto cubre y sus límites"),
 ("C", "Sabe que hay productos informales y no regulados"),
 ("H", "Está al tanto de sanciones a instituciones y de cambios en la regulación"),
 ("C", "Conoce los mecanismos de reclamación y cómo quejarse ante la autoridad"),
 ("H", "Presenta una queja cuando hace falta"),
 ("A", "Evalúa el servicio y la protección que recibe y está dispuesta a reclamar"),
 ("C", "Entiende que parte de su protección depende de leer la información que le dan"),
 ("H", "Guarda estados de cuenta, contratos y registro de conversaciones si hay maltrato"),
]),
("D", "Panorama financiero", "D2", "Derechos y obligaciones", [
 ("C", "Sabe que como usuaria tiene derechos y obligaciones"),
 ("H", "Los toma en cuenta y lee la letra chica"),
 ("A", "Valora sus derechos como usuaria"),
 ("H", "Avisa a la institución cambios en su situación cuando corresponde"),
 ("C", "Conoce derechos y obligaciones si no paga impuestos o servicios"),
 ("H", "Informa a sus acreedores lo que puede afectar sus pagos"),
 ("H", "Pide apoyo para pagar o diferir cuentas en momentos difíciles"),
 ("C", "Entiende las responsabilidades de un aval y decide con información si acepta serlo"),
]),
("D", "Panorama financiero", "D3", "Educación, información y asesoría", [
 ("C", "Sabe que hay fuentes de información, educación y asesoría, y que no todas son imparciales"),
 ("H", "Se informa como usuaria"),
 ("A", "Reconoce fuentes confiables"),
 ("C", "Sabe que puede mejorar su educación y bienestar financiero"),
 ("H", "Aprende toda la vida y usa herramientas para frenar hábitos que la perjudican"),
 ("A", "Quiere aprender y recordar datos importantes"),
 ("A", "Investiga con criterio y enseña a sus hijos sobre dinero"),
 ("C", "Sabe dónde encontrar información y cuándo sirve la asesoría independiente"),
 ("H", "Usa herramientas y fuentes independientes al decidir"),
 ("A", "Aplica lo aprendido y busca asesoría independiente cuando hace falta"),
 ("C", "Sabe el beneficio de hablar de dinero con personas de confianza"),
 ("H", "Habla de dinero con su familia de forma abierta y con profesionales"),
 ("A", "Se siente capaz de hablar de dinero y sacar conclusiones de varias opiniones"),
]),
("D", "Panorama financiero", "D4", "Productos y servicios financieros", [
 ("C", "Conoce los tipos de productos, incluidos los digitales, y qué revisar al elegir"),
 ("H", "Busca las características importantes y elige productos adecuados"),
 ("A", "Se siente capaz de decidir entre productos tradicionales y nuevos"),
 ("C", "Sabe si tiene derecho a productos financieros básicos"),
 ("H", "Revisa si sus productos le siguen conviniendo y exige calidad"),
 ("A", "Pregunta, evalúa la confianza en la institución y negocia condiciones"),
 ("C", "Sabe que el producto adecuado depende de su situación y preferencias"),
 ("C", "Conoce instituciones de su zona y en línea, y productos con criterios culturales o éticos"),
 ("H", "Elige productos acordes a sus preferencias"),
 ("C", "Sabe que escuelas, patrones, tiendas o grupos ofrecen productos financieros y los riesgos de los informales"),
 ("H", "Evalúa los productos que ofrecen organizaciones no financieras"),
 ("C", "Reconoce el papel de la publicidad y las formas de cobro de las instituciones"),
 ("H", "Evalúa con objetividad lo que se anuncia y el costo de cancelar"),
 ("H", "Busca información sobre productos útiles pero complejos"),
 ("A", "Pide mejor servicio o compensación y cambia de institución si conviene"),
 ("C", "Sabe que los servicios financieros cambian con el tiempo"),
]),
("D", "Panorama financiero", "D5", "Fraudes y estafas", [
 ("C", "Conoce los riesgos de fraude y cómo detectar señales"),
 ("H", "Protege datos personales, información financiera, contraseñas y NIP"),
 ("A", "Se siente capaz de cuestionar mensajes, ofertas y recomendaciones"),
 ("C", "Entiende la importancia de proteger sus datos y claves"),
 ("H", "Se mantiene al día sobre fraudes nuevos"),
 ("H", "Examina si mensajes y ofertas son genuinos y habla solo con representantes verificados"),
 ("A", "Acepta haberse equivocado si hay señales de fraude"),
 ("A", "Quiere aprender a evitar fraudes"),
 ("C", "Sabe a quién reportar un fraude"),
 ("H", "Reporta fraudes aunque no haya sido víctima"),
 ("A", "Se siente capaz de decir que ocurrió un fraude"),
]),
("D", "Panorama financiero", "D6", "Impuestos y gasto público", [
 ("C", "Entiende por qué se cobran impuestos y en qué se usan"),
 ("H", "Paga impuestos y pide devoluciones cuando corresponde"),
 ("A", "Acepta la importancia de pagar sus impuestos"),
 ("C", "Conoce los impuestos básicos: sobre la renta y al consumo"),
 ("H", "Da seguimiento a sus obligaciones y derechos fiscales"),
 ("C", "Sabe cómo revisar sus obligaciones y si tiene impuestos diferidos"),
 ("H", "Considera sus impuestos al presupuestar y planear"),
 ("C", "Conoce el trato fiscal de hipotecas, pensiones y ahorro"),
 ("H", "Considera el trato fiscal al elegir productos"),
]),
("D", "Panorama financiero", "D7", "Influencias externas", [
 ("C", "Entiende cómo una recesión o la inflación afectan su situación"),
 ("H", "Sigue las noticias que pueden afectar su seguridad financiera"),
 ("A", "Se siente capaz de ajustar sus planes por factores externos"),
 ("C", "Entiende que cambios en apoyos, pensiones o leyes laborales afectan sus planes"),
 ("C", "Conoce las principales instituciones que influyen en la economía"),
 ("H", "Ajusta sus planes según el efecto de factores externos"),
]),
]
