# IOSCO/OECD Core competencies framework on financial literacy for investors (2019). Paráfrasis en español de todas las competencias.
MARCO = "IOSCO/OCDE inversionistas (2019)"
TEMAS = [
("I", "Invertir", "I1", "Principios básicos de inversión", [
 ("C", "Explica la diferencia entre ahorrar e invertir"),
 ("C", "Explica la diferencia entre invertir y especular"),
 ("C", "Describe la relación entre riesgo y rendimiento"),
 ("C", "Explica el efecto de la inflación en planes e inversiones de largo plazo"),
 ("C", "Explica el efecto del interés compuesto"),
 ("C", "Explica los beneficios de diversificar"),
 ("C", "Explica el riesgo de pedir prestado para invertir"),
 ("C", "Explica el efecto de invertir montos iguales con regularidad (promediar costos)"),
 ("H", "Tiene un fondo de emergencia antes de invertir"),
 ("H", "Elige inversiones acordes a su tolerancia al riesgo y objetivos"),
 ("H", "Diversifica"),
 ("H", "Invierte solo en lo que puede explicar: características, comisiones y riesgos"),
 ("H", "Fija un objetivo para cada inversión"),
 ("H", "Revisa su tolerancia al riesgo cuando cambia su situación"),
 ("H", "Invierte con regularidad y disciplina para metas largas"),
 ("A", "Reconoce que una inversión puede subir o bajar"),
 ("A", "Reconoce que invertir sin información es más riesgoso"),
 ("A", "Ve la inversión como parte de su plan, no como apuesta"),
]),
("I", "Invertir", "I2", "Características de los productos de inversión", [
 ("C", "Identifica y compara características y riesgos de distintas clases de activos"),
 ("C", "Identifica qué factores cambian el valor de una inversión"),
 ("C", "Describe las comisiones de un producto de inversión"),
 ("H", "Compara productos de la misma clase"),
 ("H", "Usa indicadores adecuados para comparar"),
 ("H", "Calcula el rendimiento real (después de inflación, impuestos y comisiones)"),
 ("A", "Investiga antes de comprometerse, también con criterios éticos"),
 ("A", "Reconoce que el rendimiento pasado no garantiza el futuro"),
]),
("I", "Invertir", "I3", "Comprar y vender inversiones", [
 ("C", "Conoce los canales para comprar y vender y sus características"),
 ("C", "Conoce el papel del intermediario y cómo cobra"),
 ("C", "Explica el riesgo de dejar su cuenta en manos de un tercero"),
 ("C", "Identifica riesgos de ciberseguridad en plataformas"),
 ("H", "Usa varias fuentes imparciales y herramientas"),
 ("H", "Pregunta al intermediario para aclarar dudas"),
 ("H", "Busca asesoría independiente cuando hace falta"),
 ("H", "Compara pros y contras de cada canal"),
 ("H", "Revisa y guarda comprobantes de sus operaciones"),
 ("H", "Opera solo con intermediarios autorizados"),
 ("A", "Decide con información, cuestiona ofertas demasiado buenas, pregunta cómo cobra el intermediario y evalúa si confiar"),
]),
("I", "Invertir", "I4", "Dar seguimiento a sus inversiones", [
 ("C", "Entiende su estado de cuenta de inversión"),
 ("C", "Conoce las opciones ante eventos corporativos (dividendos, votaciones)"),
 ("C", "Distingue ganancias o pérdidas realizadas y no realizadas"),
 ("H", "Revisa y guarda estados de cuenta y pide copia si no se la dan"),
 ("H", "Revisa si sus inversiones siguen acordes a su perfil"),
 ("H", "Rebalancea cuando hace falta"),
 ("H", "Lee los avisos sobre sus inversiones y actúa"),
 ("A", "Se siente capaz de ajustar y quiere estar informada"),
]),
("I", "Invertir", "I5", "Derechos y obligaciones de quien invierte", [
 ("C", "Conoce sus derechos, la protección disponible y cómo reclamar"),
 ("C", "Sabe qué pasa si da información falsa o incompleta al intermediario"),
 ("C", "Sabe lo que implica firmar con un intermediario"),
 ("H", "Lee el folleto o la ficha del producto antes de comprar"),
 ("H", "Verifica con el regulador que el producto y el intermediario estén autorizados"),
 ("H", "Presenta una queja cuando hay una disputa"),
 ("H", "Aclara todo antes de firmar y guarda copia"),
 ("A", "Ejerce sus derechos, lee la letra chica, da información correcta, reconoce el riesgo de lo no regulado y asume sus decisiones"),
]),
("I", "Invertir", "I6", "Sesgos al invertir", [
 ("C", "Sabe que no siempre decidimos de forma racional"),
 ("C", "Da ejemplos de sesgos: seguir a la manada, anclarse, miedo a perder"),
 ("H", "Detecta sus sesgos"),
 ("H", "Evita decisiones impulsivas"),
 ("H", "Decide con datos"),
 ("A", "Reconoce que las emociones influyen y que la disciplina reduce los sesgos"),
]),
("I", "Invertir", "I7", "Fraudes de inversión", [
 ("C", "Describe los rasgos de los fraudes de inversión"),
 ("C", "Sabe dónde consultar fraudes reportados"),
 ("H", "Reconoce las tácticas de fraude"),
 ("H", "Cuestiona ofertas demasiado buenas"),
 ("H", "Reporta al regulador o a la autoridad"),
 ("A", "Quiere aprender a evitarlos, se siente capaz de cuestionar y de reconocer si fue víctima"),
 ("A", "Sabe que no existen inversiones de bajo riesgo y alto rendimiento"),
]),
]
