# OECD/INFE Core competencies framework on financial literacy for youth (2015), 15 a 18 años. Paráfrasis en español de todas las competencias.
MARCO = "OCDE jóvenes (2015)"
TEMAS = [
("A", "Dinero y transacciones", "J-A1", "Dinero", [
 ("C", "Conoce las formas comunes del dinero y que billetes y monedas tienen valor"),
 ("C", "Sabe que nadie tiene dinero ilimitado"),
 ("C", "Sabe que el dinero se puede guardar de varias formas, incluido un banco, y cómo retirarlo"),
 ("C", "Sabe que usar tu propio dinero en ciertos lugares puede costar una comisión"),
 ("C", "Sabe que el dinero es un activo y que un préstamo no es un regalo"),
 ("C", "Entiende el papel del dinero en su cultura"),
 ("C", "Entiende que la inflación resta valor al efectivo, y al dinero en el banco si supera los intereses"),
 ("A", "Se siente capaz de recibir dinero en efectivo y en otras formas"),
 ("A", "Habla de dinero con su familia y adultos de confianza"),
 ("A", "Quiere conocer beneficios y riesgos de nuevas formas de dinero como las criptomonedas"),
 ("H", "Reconoce y cuenta dinero en su moneda y cuida su dinero y sus cosas de valor"),
 ("H", "Compara formas de transferir dinero entre personas y organizaciones"),
 ("H", "Considera ventajas y desventajas de cada tipo de operación, para sí y para otros"),
]),
("A", "Dinero y transacciones", "J-A2", "Ingreso", [
 ("C", "Conoce las fuentes típicas de ingreso"),
 ("C", "Conoce caminos de carrera, incluido emprender"),
 ("C", "Entiende cómo la escolaridad influye en el salario"),
 ("C", "Sabe que lo que llega es menos que lo ganado por los descuentos"),
 ("C", "Entiende que el ingreso puede variar cada mes"),
 ("C", "Entiende que el ingreso aporta al bienestar propio, familiar y de la comunidad"),
 ("C", "Conoce fuentes de ingreso que le sirven hoy o pronto"),
 ("C", "Identifica oportunidades de negocio y evalúa si son viables frente a otras opciones"),
 ("A", "Se siente capaz de buscar formas de generar ingreso"),
 ("A", "Se siente capaz de hablar de sueldo al pedir trabajo"),
 ("H", "Identifica posibles fuentes de ingreso y planea tener ingreso cuando lo necesite"),
 ("H", "Identifica formas de reunir dinero emprendiendo"),
 ("H", "Hace un plan de negocio sencillo"),
]),
("A", "Dinero y transacciones", "J-A3", "Pagos y compras", [
 ("C", "Conoce formas de pago y que el dinero se cambia por bienes o servicios"),
 ("C", "Sabe que lo que gasta ya no lo tiene para otra cosa"),
 ("C", "Sabe que la tarjeta prepagada necesita saldo, que la de débito está ligada a una cuenta y que la de crédito es un préstamo"),
 ("C", "Conoce nuevas tecnologías de pago en su localidad"),
 ("C", "Sabe cuándo puede convenir una tarjeta de crédito"),
 ("C", "Sabe que algunas cuentas de débito pueden prestar con sobregiro"),
 ("C", "Sabe que algunos negocios cobran comisión por pagar con tarjeta de crédito"),
 ("A", "Es consciente de sus hábitos de gasto"),
 ("A", "Quiere comparar precios en compras diarias"),
 ("A", "Respeta que cada quien tenga preferencias distintas para gastar, ahorrar o donar"),
 ("A", "Se siente capaz de reclamar un cambio o cobro equivocado"),
 ("A", "Se siente capaz de hacer operaciones sencillas en un negocio o puesto"),
 ("A", "Decide sus gastos aunque sus amistades elijan distinto"),
 ("A", "Entiende que sus compras tienen un lado ético que afecta a otros"),
 ("A", "Se siente capaz de negociar un precio justo"),
 ("H", "Elige entre productos parecidos por precio y cantidad"),
 ("H", "Calcula mentalmente el precio final con descuento o impuesto"),
 ("H", "Paga con el monto justo o revisa su cambio, y revisa y guarda sus tickets"),
 ("H", "Compra y vende con honestidad"),
 ("H", "Piensa sus compras, sobre todo las grandes"),
 ("H", "Compara formas de pagar y cobrar"),
]),
("A", "Dinero y transacciones", "J-A4", "Precios", [
 ("C", "Tiene una idea realista del costo de lo básico, como la comida"),
 ("C", "Sabe que un mismo producto cuesta distinto en distintos lugares"),
 ("C", "Conoce el precio de lo que quieren sus pares y cómo se compara con su ingreso"),
 ("C", "Sabe que impuestos y tipo de cambio cambian el precio final"),
 ("C", "Entiende cómo la inflación y la economía cambian los precios"),
 ("C", "Entiende que el precio refleja competencia y alternativas"),
]),
("A", "Dinero y transacciones", "J-A5", "Registros y contratos", [
 ("C", "Entiende que documentos, recibos y garantías son importantes y se guardan"),
 ("C", "Entiende que algunos documentos tienen efectos legales y deben leerse"),
 ("C", "Entiende que firmar un contrato puede obligarle a pagar y que hay consecuencias si no cumple"),
 ("A", "Se toma el tiempo de leer un contrato antes de firmar"),
 ("A", "Se siente capaz de leer documentos financieros y pedir corregir errores"),
 ("H", "Lee, revisa y cuida sus documentos financieros"),
 ("H", "Detecta irregularidades en un estado de cuenta"),
 ("H", "Llena formularios con cuidado"),
 ("H", "Hace los cálculos para revisar tickets y su gasto"),
 ("H", "Lee términos y condiciones y aclara palabras antes de firmar"),
]),
("A", "Dinero y transacciones", "J-A6", "Moneda extranjera", [
 ("C", "Sabe que otros países usan otras monedas y dónde cambiarlas"),
 ("C", "Sabe que el tipo de cambio varía, que cambiar tiene costo y que depende del proveedor"),
 ("C", "Entiende por qué varía el tipo de cambio y cómo afecta precios locales"),
 ("H", "Paga en otra moneda si hace falta"),
 ("H", "Convierte montos con el tipo de cambio"),
 ("H", "Decide con cuidado compras en otra moneda"),
]),
("B", "Planear y administrar", "J-B1", "Presupuesto", [
 ("C", "Entiende el beneficio de planear y hacer un presupuesto"),
 ("C", "Entiende que debe registrar todos sus gastos para saber si cumple"),
 ("C", "Entiende por qué revisar su flujo en distintos plazos"),
 ("H", "Vive con lo que tiene, considerando el apoyo que recibe"),
 ("H", "Usa herramientas sencillas de presupuesto"),
 ("H", "Distingue ingresos y gastos regulares e irregulares y hace su presupuesto"),
 ("H", "Vigila sus gastos e ingresos y ajusta"),
 ("H", "Identifica cómo sus planes de 1 a 2 años le afectarán en dinero"),
]),
("B", "Planear y administrar", "J-B2", "Administrar ingresos y gastos", [
 ("C", "Distingue necesidades y deseos"),
 ("C", "Entiende que con poco ingreso hay que priorizar"),
 ("C", "Entiende que hay gastos irregulares y que hay que planearlos"),
 ("C", "Entiende que el dinero se administra activamente"),
 ("C", "Sabe que se puede suavizar el gasto ahorrando o pidiendo prestado"),
 ("C", "Argumenta cuándo conviene pedir prestado y cuándo esperar y ahorrar"),
 ("C", "Entiende por qué separar el dinero personal del de un negocio"),
 ("A", "Quiere manejar bien su dinero y se siente capaz de administrar gasto y ahorro"),
 ("A", "Mantiene la motivación ante tropiezos financieros"),
 ("H", "Piensa opciones para gastar o ahorrar lo que recibe"),
 ("H", "Evita gastar de más en el día a día"),
 ("H", "Se prepara para gastos cercanos y decide a tiempo"),
 ("H", "Revisa sus decisiones pasadas para aprender"),
 ("H", "Compara productos por varios factores para sus metas de corto plazo"),
]),
("B", "Planear y administrar", "J-B3", "Ahorro", [
 ("C", "Conoce los beneficios de ahorrar y que a veces hay que ahorrar para algo caro"),
 ("C", "Sabe cómo las tasas de interés afectan el ahorro"),
 ("C", "Entiende el interés compuesto"),
 ("C", "Conoce el interés típico del ahorro que usan sus pares"),
 ("C", "Sabe cómo la inflación afecta el ahorro y por qué ver inflación y tasa juntas"),
 ("A", "Quiere ahorrar para algo concreto"),
 ("A", "Se siente capaz de elegir dónde ahorrar"),
 ("A", "Es optimista sobre ahorrar a largo plazo"),
 ("H", "Explica los beneficios de ahorrar"),
 ("H", "Calcula cuánto tardará en juntar una cantidad"),
 ("H", "Decide con información si ahorrar mientras paga una deuda"),
 ("H", "Hace un plan para una meta grande"),
 ("H", "Considera que el precio de lo que quiere puede cambiar"),
]),
("B", "Planear y administrar", "J-B4", "Planear a largo plazo", [
 ("C", "Entiende el beneficio de planear para eventos futuros de la vida"),
 ("C", "Sabe que conviene ahorrar para el retiro desde joven"),
 ("C", "Sabe armar un portafolio de inversión sencillo"),
 ("C", "Entiende la importancia de planear estudios y vida independiente"),
 ("C", "Sabe cómo edad, ingreso y circunstancias afectan sus decisiones"),
 ("C", "Entiende el papel de las pensiones en el retiro"),
 ("C", "Conoce formas de construir patrimonio para personas, familias y comunidades"),
 ("C", "Entiende por qué muchas personas combinan ahorro y crédito"),
 ("A", "Está dispuesta a esperar para ganar más después"),
 ("A", "Se siente capaz de planear varios meses para una meta"),
 ("A", "Le interesan con cautela los productos y proveedores nuevos"),
 ("H", "Decide con información, y con su familia, si seguir estudiando o trabajar"),
 ("H", "Identifica etapas de vida que requieren prepararse desde joven"),
 ("H", "Evalúa pros y contras de productos para metas largas"),
]),
("B", "Planear y administrar", "J-B5", "Crédito", [
 ("C", "Entiende que si pide prestado debe pagar"),
 ("C", "Entiende por qué se pagan intereses por un préstamo y se reciben por ahorrar"),
 ("C", "Conoce las dificultades de quien debe mucho"),
 ("C", "Sabe que lo comprado a crédito se puede perder si no paga"),
 ("C", "Sabe que las tasas cambian el costo de algunos créditos"),
 ("C", "Sabe que «compra ahora, paga después» es crédito"),
 ("C", "Entiende qué influye en el costo y acceso al crédito y el valor de un buen historial"),
 ("C", "Conoce el interés y las comisiones típicas del crédito que usan sus pares"),
 ("C", "Explica por qué pedir prestado para producir, como abrir un negocio, puede tener más sentido que para consumir"),
 ("A", "Pide consejo antes de usar crédito"),
 ("A", "Se siente capaz de decidir sobre formas comunes de crédito"),
 ("H", "Paga a tiempo lo que debe"),
 ("H", "Habla pronto con quien le prestó si tiene problemas"),
 ("H", "Entiende el costo total de pedir prestado"),
 ("H", "Explica las consecuencias de no pagar"),
 ("H", "Calcula el beneficio de pagar antes"),
]),
("C", "Riesgo y recompensa", "J-C1", "Cambio de valor", [
 ("C", "Entiende que algunas compras pierden valor y otras lo ganan"),
 ("C", "Entiende que las inversiones pueden ganar o perder valor"),
 ("C", "Sabe que los productos de inversión tienen distintos riesgos"),
]),
("C", "Riesgo y recompensa", "J-C2", "Identificar riesgos", [
 ("C", "Conoce riesgos con efecto financiero, como inundaciones o enfermedades"),
 ("C", "Sabe que pagar tarde tiene consecuencias"),
 ("C", "Entiende que hay que revisar las características de un producto para ver su riesgo"),
 ("C", "Sabe que algunas empresas o prestamistas informales solo muestran beneficios"),
 ("C", "Identifica trucos de precios y publicidad engañosa"),
 ("C", "Sabe que invertir, estudiar o elegir afore implica riesgos calculados"),
 ("C", "Entiende por qué vivir muchos años es un riesgo para el retiro"),
 ("C", "Entiende el papel y el riesgo de ser aval"),
 ("A", "Es cautelosa al decidir con prisa o sin buena información"),
 ("A", "Aplica la regla «si parece demasiado bueno, probablemente no lo es»"),
 ("A", "Se atreve a tomar riesgos calculados"),
 ("H", "Cuida su dinero y sus cosas para no perderlos"),
 ("H", "Estima de forma sencilla la probabilidad de eventos con efecto financiero"),
 ("H", "Distingue una inversión real de un fraude como una pirámide"),
]),
("C", "Riesgo y recompensa", "J-C3", "Redes de protección y seguros", [
 ("C", "Sabe que algunas personas ahorran para sentirse seguras"),
 ("C", "Sabe cómo el ahorro y los seguros ayudan a manejar riesgos"),
 ("C", "Entiende por qué la gente compra seguros y conoce algunos (viaje, auto)"),
 ("C", "Entiende por qué decir la verdad al contratar un seguro"),
 ("C", "Conoce los apoyos de gobierno y sus límites"),
 ("C", "Sabe si tiene obligación legal de asegurarse ante algo"),
 ("H", "Explica para qué sirve un seguro"),
 ("H", "Decide si un seguro sencillo le sirve hoy"),
 ("H", "Revisa si su hogar ya tiene protección antes de contratar"),
 ("H", "Decide sobre seguros al comprar o viajar y si valen lo que cuestan"),
]),
("C", "Riesgo y recompensa", "J-C4", "Equilibrar riesgo y rendimiento", [
 ("C", "Sabe que los productos tienen riesgos y beneficios y que más rendimiento suele implicar más riesgo"),
 ("C", "Entiende la diversificación"),
 ("C", "Compara el riesgo de ahorrar en un banco con invertir en bolsa"),
 ("C", "Sabe por qué a quien emprende le cuesta conseguir inversionistas o préstamos"),
 ("C", "Entiende riesgos y beneficios de trabajar por su cuenta o como empleada"),
 ("C", "Entiende que el rendimiento pasado no garantiza el futuro y que las subidas y bajadas cortas no son la tendencia"),
 ("A", "Asume las consecuencias, buenas y malas, de sus decisiones"),
 ("H", "Pide consejo a fuentes confiables antes de decidir"),
 ("H", "Aprende de su experiencia y la de otros"),
 ("H", "Evalúa riesgos y beneficios de negocios sencillos"),
 ("H", "Analiza productos e inversiones y su desempeño"),
 ("H", "Analiza riesgos y beneficios de tener oro o una propiedad"),
]),
("D", "Panorama financiero", "J-D1", "Regulación y protección al usuario", [
 ("C", "Conoce a los reguladores y autoridades financieras de su país y su papel"),
 ("C", "Sabe que hay un seguro que protege ciertos depósitos"),
 ("A", "Se siente capaz de ejercer sus derechos y de quejarse"),
 ("A", "Asume la responsabilidad de lo que controla"),
 ("H", "Busca si hay quejas sobre un producto antes de contratarlo"),
 ("H", "Presenta quejas cuando hace falta"),
 ("H", "Se informa sobre productos nuevos que se ofrecen cerca"),
]),
("D", "Panorama financiero", "J-D2", "Educación, información y asesoría", [
 ("C", "Sabe que seguir aprendiendo sobre su dinero le ayuda a decidir mejor"),
 ("C", "Sabe dónde encontrar consejo sencillo y confiable, incluidas fuentes de gobierno"),
 ("C", "Distingue información imparcial de publicidad"),
 ("C", "Sabe que hay calculadoras y comparadores y que hay que ver si son imparciales"),
]),
("D", "Panorama financiero", "J-D3", "Derechos y obligaciones", [
 ("C", "Entiende que instituciones y usuarios tienen derechos y obligaciones"),
 ("C", "Sabe que la institución debe tratarle con justicia y que puede quejarse"),
 ("C", "Sabe que incumplir tiene consecuencias para ambas partes"),
]),
("D", "Panorama financiero", "J-D4", "Instituciones financieras", [
 ("C", "Sabe que varias instituciones ofrecen productos parecidos y conviene comparar"),
 ("C", "Sabe que las instituciones formales están reguladas"),
 ("C", "Entiende que un producto «sin costo» también le deja ganancia a la institución"),
 ("C", "Sabe comparar con herramientas"),
 ("C", "Sabe que algunas instituciones deben ofrecer cuentas básicas"),
 ("C", "Sabe que algunas empresas no financieras que ofrecen servicios no están reguladas igual"),
 ("C", "Sabe que hay quien ahorra o presta sin regulación, de forma informal o ilegal"),
 ("H", "Identifica instituciones formales antes de contratar"),
 ("H", "Investiga los productos antes de contratar"),
 ("H", "Distingue la información de su institución de la publicidad"),
]),
("D", "Panorama financiero", "J-D5", "Fraudes y estafas", [
 ("C", "Sabe para qué sirven el NIP y otras medidas de seguridad"),
 ("C", "Sabe cuidar sus datos, también al comprar en línea"),
 ("C", "Entiende por qué cuidar con quién habla de su situación financiera"),
 ("C", "Conoce fraudes comunes y cómo protegerse"),
 ("H", "Protege datos, contraseñas y dinero"),
 ("H", "Evalúa si un mensaje de una institución es real o fraude"),
 ("H", "Actúa para resolver si fue víctima"),
]),
("D", "Panorama financiero", "J-D6", "Impuestos, gasto público e influencias externas", [
 ("C", "Entiende que el gobierno cobra impuestos para servicios públicos"),
 ("C", "Tiene una idea general del sistema de impuestos"),
 ("C", "Sabe que los cambios en impuestos y apoyos afectan el gasto y el ahorro"),
 ("C", "Identifica políticas que apoyan a quienes emprenden"),
 ("C", "Sabe que la publicidad y otros factores influyen en sus decisiones"),
 ("C", "Entiende cómo el panorama financiero influye en abrir un negocio"),
 ("C", "Entiende que sus decisiones afectan a su familia y su comunidad"),
]),
]
