# OECD/INFE Core competencies framework on financial literacy for MSMEs (2018). Paráfrasis en español de todas las competencias.
# Etapa: B = básica/informal · I = inicio/formal · CR = crecer · CI = cierre. Dimensión: C, H, A.
MARCO = "OCDE negocios (2018)"
TEMAS = [
("A", "Elegir y usar servicios financieros", "N-A1", "Pagos y depósitos del negocio", [
 ("C", "I: Entiende ventajas, límites e implicaciones de usar pagos y depósitos formales"),
 ("C", "I: Conoce servicios de pago y depósito para el negocio, incluidos digitales, y su costo"),
 ("C", "I: Conoce las comisiones por cobrar a clientes (terminal, pago sin contacto)"),
 ("H", "I: Elige el servicio de pago y depósito por precio, costo por operación, calidad y preferencias de clientes y proveedores"),
 ("H", "I: Compara proveedores y productos"),
 ("H", "I: Tiene cuentas separadas para lo personal y el negocio"),
 ("A", "I: Se siente capaz de hablar con instituciones sobre las necesidades del negocio y de comparar"),
 ("C", "CR: Conoce costos de cambio de moneda y operaciones en otra moneda"),
 ("H", "CR: Opera en otra moneda si hace falta y revisa si sus servicios siguen conviniendo"),
 ("A", "CR: Se siente capaz de operar en otra moneda"),
]),
("A", "Elegir y usar servicios financieros", "N-A2", "Financiar el negocio", [
 ("C", "B: Sabe cuánto dinero necesita para arrancar y cuánto debe conseguir fuera"),
 ("C", "B: Entiende lo que implica financiarse con familia y amistades u otras fuentes"),
 ("H", "B: Calcula el costo real de arrancar y planea cómo cubrirlo"),
 ("H", "B: Decide cómo financiarse comparando opciones y proveedores"),
 ("A", "B: Se siente capaz de comparar productos y proveedores de financiamiento"),
 ("C", "I: Conoce opciones de financiamiento: propio o familiar, público o privado, deuda o capital"),
 ("C", "I: Conoce productos de financiamiento externo, sus beneficios y riesgos"),
 ("C", "I: Entiende el papel de la garantía y del aval"),
 ("C", "I: Sabe que algunas deudas del negocio las responde personalmente"),
 ("C", "I: Entiende cómo deciden bancos e inversionistas, para ser sujeto de crédito"),
 ("C", "I: Conoce apoyos públicos o sin fines de lucro, incluidas incubadoras"),
 ("C", "I: Conoce beneficios, riesgos y costos del financiamiento digital (fondeo colectivo, préstamos entre personas, criptoactivos)"),
 ("C", "I: Entiende si un producto es adecuado al tamaño y etapa del negocio"),
 ("C", "I: Entiende cómo funciona el historial crediticio del negocio"),
 ("H", "I: Investiga y accede a créditos, apoyos y garantías de gobierno"),
 ("H", "I: Elige la mejor opción y una buena mezcla de fuentes"),
 ("H", "I: Prepara documentos, plan de negocio y una presentación para conseguir capital"),
 ("H", "I: Cumple requisitos de bancos e inversionistas y las condiciones de pago"),
 ("H", "I: Mantiene informados a sus financiadores"),
 ("H", "I: Cuida y revisa su historial crediticio"),
 ("A", "I: Se siente capaz de acercarse a financiadores, defiende su plan con optimismo y no se rinde ante un rechazo"),
 ("C", "CR: Entiende qué financiamiento conviene para crecer y cómo funcionan los mercados de capital"),
 ("H", "CR: Elige el financiamiento de crecimiento según etapa, riesgo y monto"),
 ("A", "CR: Actúa con anticipación ante temas financieros del crecimiento"),
]),
("B", "Administrar y planear el negocio", "N-B1", "Registro, impuestos y obligaciones legales", [
 ("C", "I: Conoce las figuras legales del negocio y sus implicaciones legales, fiscales y financieras"),
 ("C", "I: Sabe que en algunas figuras responde con sus bienes personales"),
 ("C", "I: Entiende ventajas y límites de formalizarse"),
 ("C", "I: Conoce requisitos legales: licencias, seguros, marcas, patentes, impuestos y estados financieros"),
 ("C", "I: Sabe si debe cumplir requisitos de debida diligencia"),
 ("C", "I: Conoce los impuestos del negocio y su obligación de pagarlos o enterarlos"),
 ("C", "I: Conoce reducciones o estímulos fiscales para pequeños negocios"),
 ("H", "I: Elige la figura legal, con asesoría si hace falta"),
 ("H", "I: Cumple a tiempo estados financieros, licencias, declaraciones y seguros obligatorios"),
 ("A", "I: Se organiza para cumplir plazos y se adelanta a sus obligaciones"),
 ("C", "CR: Conoce trámites para contratar personal: nómina, seguridad social, salud y seguridad"),
 ("C", "CR: Conoce opciones para llevar la nómina (propia, contador, software)"),
 ("H", "CR: Elige y revisa cómo llevar la nómina"),
 ("C", "CI: Conoce requisitos legales y fiscales para cerrar o traspasar, y de la quiebra"),
 ("H", "CI: Cumple a tiempo las obligaciones del cierre: impuestos, seguros, licencias y personal"),
]),
("B", "Administrar y planear el negocio", "N-B2", "Registros y contabilidad", [
 ("C", "B: Entiende ingresos, ganancia, bienes y deudas del negocio y cómo se relacionan"),
 ("C", "B: Conoce todos los ingresos y gastos regulares del negocio"),
 ("C", "B: Distingue costos fijos y variables"),
 ("H", "B: Registra por escrito las operaciones del negocio"),
 ("H", "B: Da seguimiento a ingresos y costos"),
 ("H", "B: Proyecta el flujo de efectivo y un presupuesto de corto plazo"),
 ("H", "B: Sabe si el negocio gana o pierde"),
 ("A", "B: Es constante para llevar costos, ingresos y ganancias"),
 ("C", "I: Entiende balance, flujo de efectivo y estado de resultados"),
 ("C", "I: Conoce opciones de contabilidad (software, contador) y sus pros y contras"),
 ("H", "I: Guarda comprobantes de ingresos, pagos y contratos para contabilidad, seguros e impuestos"),
 ("H", "I: Elige y revisa su solución de contabilidad"),
 ("A", "I: Está decidida a llevar registros y se siente capaz de elegir cómo"),
]),
("B", "Administrar y planear el negocio", "N-B3", "Finanzas de corto plazo", [
 ("C", "B: Entiende por qué separar dinero personal y del negocio"),
 ("C", "B: Sabe que depreciación y plazos de clientes y proveedores afectan el flujo"),
 ("C", "B: Entiende inflación, interés, tipo de cambio y depreciación"),
 ("H", "B: Separa sus finanzas personales de las del negocio"),
 ("H", "B: Se paga un sueldo y lo trata como gasto del negocio"),
 ("H", "B: Aparta dinero para arrancar y operar mientras llega la ganancia"),
 ("H", "B: Revisa el flujo seguido para anticipar faltantes"),
 ("H", "B: Administra ingresos y costos para pagar gastos regulares y compara lo real con lo proyectado"),
 ("A", "B: Tiene disciplina para separar y revisar el flujo, y mira hacia adelante"),
 ("C", "I: Entiende cómo los pagos de créditos afectan el flujo y los productos de corto plazo"),
 ("C", "I: Conoce indicadores financieros de su giro"),
 ("H", "I: Usa indicadores para administrar el corto plazo"),
 ("H", "I: Administra ingresos, costos e inventario para pagar proveedores, impuestos y créditos a tiempo"),
 ("H", "I: Puede conseguir liquidez rápida si hay un faltante"),
 ("H", "I: Evalúa y maneja el atraso de clientes (selección, anticipos, seguro de crédito)"),
 ("H", "I: Identifica qué productos o servicios dejan más ganancia"),
 ("A", "I: Es puntual con sus pagos y se adelanta a sus necesidades de efectivo"),
]),
("B", "Administrar y planear el negocio", "N-B4", "Planear más allá del corto plazo", [
 ("C", "I: Entiende conceptos de planeación como el interés compuesto"),
 ("C", "I: Entiende indicadores de desempeño para planear"),
 ("H", "I: Administra pensando en impuestos, deudas, equipo, crecimiento y faltantes futuros"),
 ("H", "I: Cuadra fechas de ingresos y pagos de deudas"),
 ("H", "I: Busca subir ingresos (precio, promoción) y bajar costos"),
 ("A", "I: Tiene paciencia y expectativas realistas, y cumple lo planeado"),
 ("C", "CR: Conoce los gastos de crecer y cómo financiarlos"),
 ("C", "CR: Entiende lo que implica contratar y cumplir la ley laboral"),
 ("H", "CR: Hace planes y presupuestos de mediano plazo"),
 ("H", "CR: Analiza si crecer es viable y rentable, y si una inversión conviene"),
 ("A", "CR: Detecta oportunidades, planea a largo plazo y considera la ética y la sostenibilidad"),
 ("C", "CI: Entiende las implicaciones de traspasar, vender, cerrar o quebrar"),
 ("C", "CI: Sabe estimar el valor de su negocio"),
 ("H", "CI: Planea con tiempo el cierre, venta o sucesión y prepara las finanzas"),
 ("A", "CI: Piensa desde antes en su salida"),
]),
("C", "Riesgos y seguros", "N-C1", "Riesgos y seguros personales de quien emprende", [
 ("C", "B: Entiende que debe cubrir su retiro y su salud"),
 ("H", "B: Evalúa si su seguridad social basta y la complementa"),
 ("A", "B: Atiende con anticipación su salud y su retiro"),
 ("H", "I: Considera un seguro de vida"),
]),
("C", "Riesgos y seguros", "N-C2", "Riesgos y seguros del negocio", [
 ("C", "B: Entiende qué hace variar el flujo: fallas, ventas, robo, daño, enfermedad, muerte, daños a terceros"),
 ("H", "B: Tiene un plan para gastos inesperados"),
 ("A", "B: Toma riesgos controlados y está preparada para la incertidumbre"),
 ("C", "I: Entiende que hay seguros además de los obligatorios y otras formas de reducir riesgos"),
 ("H", "I: Identifica riesgos en distintos plazos y hace planes de contingencia con el peor escenario"),
 ("H", "I: Asegura equipo y bienes clave y revisa su póliza"),
 ("H", "I: Aparta un fondo para temporadas bajas o emergencias"),
 ("H", "I: Diversifica clientes, productos o lugares"),
 ("H", "I: Considera el costo de quejas o de perder reputación"),
 ("A", "I: Tiene paciencia para manejar cambios"),
 ("C", "CR: Entiende los riesgos del crecimiento y que un fondo demasiado grande frena el negocio"),
 ("H", "CR: Maneja el tipo de cambio y los riesgos de mercados nuevos"),
 ("A", "CR: Se adapta cuando cambian las circunstancias"),
]),
("D", "Panorama financiero", "N-D1", "Influencias externas", [
 ("C", "B: Entiende que el mercado local y la competencia afectan al negocio y que el negocio afecta a su comunidad"),
 ("H", "B: Sigue las noticias que afectan al negocio"),
 ("C", "I: Entiende el papel de los actores económicos y cómo inflación, recesión, apoyos e impuestos afectan al negocio"),
 ("C", "I: Entiende el efecto de sus decisiones en la comunidad, la sociedad y el ambiente"),
 ("H", "I: Vigila cambios económicos y legales y reduce impactos negativos"),
 ("H", "CR: Usa el panorama económico para su estrategia y ajusta sus planes"),
 ("A", "CR: Aprovecha los cambios del entorno para crecer"),
]),
("D", "Panorama financiero", "N-D2", "Protección financiera del negocio", [
 ("C", "B: Entiende los riesgos de productos y prestamistas informales o no regulados"),
 ("H", "B: Protege los datos e información financiera del negocio"),
 ("A", "B: Está alerta ante fraudes"),
 ("C", "I: Conoce el papel del regulador y los derechos del negocio como usuario"),
 ("C", "I: Conoce cómo quejarse y resolver disputas con instituciones"),
 ("H", "I: Se informa de fraudes y ventas engañosas a negocios y los evita"),
 ("H", "I: Aplica ciberseguridad y revisa su historial por si hubo fraude"),
 ("H", "I: Verifica que la institución esté regulada"),
 ("H", "I: Reclama y busca reparación cuando hace falta"),
 ("A", "I: Protege sus datos y se siente capaz de reclamar"),
]),
("D", "Panorama financiero", "N-D3", "Información, educación y asesoría", [
 ("C", "B: Conoce lo que le falta saber y que no toda la información es confiable"),
 ("H", "B: Distingue fuentes confiables"),
 ("A", "B: Aprende de muchas fuentes"),
 ("C", "I: Conoce opciones para capacitarse, mentorías, asociaciones, incubadoras y aceleradoras, y su costo"),
 ("H", "I: Llena sus huecos de conocimiento y busca asesoría profesional cuando hace falta"),
 ("H", "I: Apoya la educación financiera de su personal"),
 ("A", "I: Quiere seguir aprendiendo"),
]),
]
